name: notparx-user-service - Build and deploy container app to Azure Web App

on:
  workflow_dispatch:
  push:
    branches: [main, dev, NOT-33/containers]

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://notparx.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_1820ced56cac4a868f699b216bf78bdc }}
          password: ${{ secrets.AzureAppService_ContainerPassword_b8d0b249c1c747b6bf3d826ca2818362 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: notparx.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1820ced56cac4a868f699b216bf78bdc }}/user-service:${{ github.sha }}
          file: ./backend/user_service/Docker_user_service

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "notparx-user-service"
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_fe639ed4c55a4454b8c1d9148ada97ee }}
          images: "notparx.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1820ced56cac4a868f699b216bf78bdc }}/user-service:${{ github.sha }}"
